<?php

use Illuminate\Database\Seeder;

class PlayersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $players = [
        		[
                	'id' => 1,
                	'first_name' 	=> 'Amos',
                	'last_name' 	=> 'Ayodeji',
                	'dob'			=> '1982-04-04',
                    'gender'        => 'male',
                    'country'       => 'Nigeria',
                	'birth_place'	=> 'Osun',
                	'residence'		=> 'Lagos',
            		'hand_type'		=> 'left',
            		'height'		=> 34,
            		'weight'		=> 58,
            		'singles_ranking' 	=> 1,
            		'doubles_ranking'	=> 1,
                    'avatar'            => '',
                    'year_turned_pro'   => '1994-04-08',
                    'career_matches_won'       => 15,
                    'career_matches_lost'      => 36,
                    'year_to_date_matches_won'       => 2,
                    'year_to_date_matches_lost'      => 0,
                    'aces'              => 3,
                    'double_faults'     => 3,
                    'unforced_errors'   => 3,
                    'total_points_won'  => 16,
                    'break_points_won'  => 5,
                    'distance_covered'  => 60.5,
                	'created_at' 	=> '2017-04-04 13:42:19',
                	'updated_at' 	=> '2017-04-04 13:42:19',
                	'deleted_at'	=> '2017-04-04 13:42:19',
            	],
            	[
                	'id' => 2,
                	'first_name' => 'Frank',
                	'last_name' => 'Osanogie',
                	'dob'		=>  '1984-04-04',
                    'gender'        => 'male',
                    'country'       => 'Nigeria',
                	'birth_place'=> 'Abuja',
                	'residence'	=> 'Edo state',
            		'hand_type'	=> 'left',
            		'height'	=> 55,
            		'weight'	=> 67,
            		'singles_ranking' 	=> 2,
            		'doubles_ranking'	=> 2,
                    'avatar'            => '',
                    'year_turned_pro'   => '1995-06-10',
                    'career_matches_won'       => 25,
                    'career_matches_lost'      => 10,
                    'year_to_date_matches_won'       => 5,
                    'year_to_date_matches_lost'      => 3,
                    'aces'              => 2,
                    'double_faults'     => 3,
                    'unforced_errors'   => 4,
                    'total_points_won'  => 20,
                    'break_points_won'  => 5,
                    'distance_covered'  => 60.5,
                	'created_at' 	=> '2017-03-04 13:42:19',
                	'updated_at' 	=> '2017-03-04 13:42:19',
                	'deleted_at'	=> '2017-03-04 13:42:19',
            	],
            	[
                	'id' => 3,
                	'first_name' => 'Stella',
                	'last_name' => 'Demuren',
                	'dob'		=>  '1986-04-04',
                    'gender'        => 'female',
                    'country'       => 'Nigeria',
                	'birth_place'=> 'Abia',
                	'residence'	=> 'Abuja',
            		'hand_type'	=> 'right',
            		'height'	=> 74,
            		'weight'	=> 48,
            		'singles_ranking' 	=> 3,
            		'doubles_ranking'	=> 3,
                    'avatar'            => '',
                    'year_turned_pro'   => '1996-01-09',
                    'career_matches_won'       => 51,
                    'career_matches_lost'      => 10,
                    'year_to_date_matches_won'       => 9,
                    'year_to_date_matches_lost'      => 6,
                    'aces'              => 2,
                    'double_faults'     => 3,
                    'unforced_errors'   => 3,
                    'total_points_won'  => 16,
                    'break_points_won'  => 5,
                    'distance_covered'  => 60.5,
                	'created_at' 	=> '2017-04-04 13:42:19',
                	'updated_at' 	=> '2017-04-04 13:42:19',
                	'deleted_at'	=> '2017-04-04 13:42:19',
            	],
            	[
                	'id' => 4,
                	'first_name' => 'Pauline',
                	'last_name'  => 'Megson',
                	'dob'		 => '1983-04-04',
                    'gender'     => 'female',
                    'country'    => 'Nigeria',
                	'birth_place'=> 'Benin',
                	'residence'	 => 'Benin',
            		'hand_type'	 => 'right',
            		'height'	 => 74,
            		'weight'	 => 48,
            		'singles_ranking' 	=> 4,
            		'doubles_ranking'	=> 4,
                    'avatar'            => '',
                    'year_turned_pro'   => '1993-11-05',
                    'career_matches_won'       => 43,
                    'career_matches_lost'      => 11,
                    'year_to_date_matches_won'       => 13,
                    'year_to_date_matches_lost'      => 6,
                    'aces'              => 3,
                    'double_faults'     => 3,
                    'unforced_errors'   => 3,
                    'total_points_won'  => 16,
                    'break_points_won'  => 5,
                    'distance_covered'  => 66.5,
                	'created_at' 	=> '2017-04-04 13:42:19',
                	'updated_at' 	=> '2017-04-04 13:42:19',
                	'deleted_at'	=> '2017-04-04 13:42:19',
            	],


        ];

        DB::table('players')->insert($players);
    }
}
